### ISSUE TITLE
@Cacheable causes ThreadLocal leak in OpenTracing

### ISSUE THREAD

**Issue by David-16** [micronaut-projects/micronaut-cache#114]
Thanks for reporting an issue for Micronaut, please review the task list below before submitting the
issue. Your issue report will be closed if the issue is incomplete and the below tasks not completed.

NOTE: If you are unsure about something and the issue is more of a question a better place to ask questions is on Stack Overflow (http://stackoverflow.com/tags/micronaut) or Gitter (https://gitter.im/micronautfw/). DO NOT use the issue tracker to ask questions.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Please clone this repository and follow the steps in this project's readme: https://github.com/David-16/micronaut-issues/tree/master/tracing-issue-3

A service calls a remote service that returns a reactive type but caches the result using `@Cacheable`.  Subsequent calls then have the OpenTracing context left over from the previous call.  Non-reactive methods do not exhibit this issue

Educated Guess: The `@Cacheable` interceptor somehow causes the OpenTracing context to not unwind correctly, leaving the OpenTracing ThreadLocal on the thread and thus making it visible to other threads which can pose a security issue.  I suspect this is because it creates a Scope that it does not close.  See README in the mentioned repository for code pointers & observations

### Expected Behaviour

The OpenTracing context should not be affected by `@Cacheable`

### Actual Behaviour

Calling a method with `@Cacheable` causes the OpenTracing context to not unwind correctly, leaving the OpenTracing ThreadLocal on the thread and thus making it visible to other threads

### Environment Information

- **Operating System**: Linux, Mac
- **Micronaut Version:** 1.3.4
- **JDK Version:** 8 & 11

### Example Application

https://github.com/David-16/micronaut-issues/tree/master/tracing-issue-3

**Comment by graemerocher** [comment]
I am not able to reproduce this with Micronaut 2.0 master and master of Micronaut cache. There have been significant changes to our instrumentation logic and it is likely this was fixed along the way. Thanks for the report.

**Comment by David-16** [comment]
Sorry for late response.  This issue still exists in 2.0.0.M3 with the same reproducer I originally gave.  Just modify `pom.xml` to point to `2.0.0.M3` instead of `1.3.4`

Note that the dependencies are suspicious.  Specifically, `io.micronaut:micronaut-bom:2.0.0.M3` has following property:
```
    <micronaut.cache.version>2.0.0.M1</micronaut.cache.version>
```

This means `io.micronaut.cache:micronaut-cache-caffeine:2.0.0.M1` gets added as a dependency management tag

This dependency in turn depends on `io.micronaut:micronaut-bom:2.0.0.M2` (M2 not M3 and a forward reference).  Maven probably resolves all this and it is not likely an issue by itself, but I would assume M3 bom would point to M3 cache dependencies.  They may be versioned separately which is fine, but the docs assume the versions align.  For example, all cache related links are broken in the [M3 docs](https://docs.micronaut.io/2.0.0.M3/guide/index.html#caching) (the links work if you change M3 to M1).

1. Is this expected?
2. Are you testing against micronaut-cache M1 (it should still fail) or an M3 version that is not yet promoted?
